name: Build_and_Test

on:
  push:
    branches:
      - develop
      - staging

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v4

    - name: Debug folder structure
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: SUContent-SEDO-Regular-Exam-2024-10-2

    - name: Build solution
      run: dotnet build --no-restore
      working-directory: SUContent-SEDO-Regular-Exam-2024-10-2

    - name: Run Unit Tests
      if: github.ref == 'refs/heads/develop'
      run: dotnet test Homes.UnitTests/Homes.UnitTests.csproj --no-build --verbosity normal
      working-directory: SUContent-SEDO-Regular-Exam-2024-10-2

    - name: Run Integration Tests
      if: github.ref == 'refs/heads/staging'
      run: dotnet test Homes.IntegrationTests/Homes.IntegrationTests.csproj --no-build --verbosity normal
      working-directory: SUContent-SEDO-Regular-Exam-2024-10-2
